name: Bug Report
description: Report a bug in MenuBrowser
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open MenuBrowser
        2. Click on...
        3. See error
    validations:
      required: true
  - type: input
    id: macos-version
    attributes:
      label: macOS version
      placeholder: "e.g. 26.0"
    validations:
      required: true
