name: Feature Request
description: Suggest a new feature
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: Describe the feature
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      placeholder: Why do you need this?
    validations:
      required: true
